##use with docker hub image
services:
  composr:
    image: vansmak/composr:latest
    container_name: composr
    ports:
      - "5003:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/joe/docker:/app/projects  # Mounting your docker folder as /app/projects
      - /home/joe/config/composr:/app/data
      ##optionals
      - /home/joe/config/caddy:/caddy_config
      - /path1:/path1                            # EXTRA_COMPOSE_DIRS path1
      - /path2:/path2                            # EXTRA_COMPOSE_DIRS path2
      - /path3:/path3etc                         # EXTRA_COMPOSE_DIRS path3
    environment:
      - DEBUG=false
      - COMPOSE_DIR=/app/projects
      - METADATA_DIR=/app/data
      - CONTAINER_METADATA_FILE=/app/data/metadata.json
      ###optionals
      - EXTRA_COMPOSE_DIRS: /path1:/path2:/path3   # Optional
      - CADDY_CONFIG_DIR=/caddy_config
    restart: unless-stopped
