## use this build and run locally 
version: '3'
services:
  composr:
    build: .
    container_name: composr-local
    ports:
      - "5003:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./:/app  # Mount code for development
      - /home/joe/docker:/home/joe/docker  # Your home directory with all compose files
      - /home/joe/projects:/home/joe/projects
      - ./metadata:/app/metadata  # Store metadata persistently
    environment:
      - COMPOSE_DIR=/home/joe/docker  # Look for compose files here
      - EXTRA_COMPOSE_DIRS=/home/joe/projects  # Extra directories to scan, my example
      - METADATA_DIR=/app/metadata  # Store settings here
      - CADDY_CONFIG_DIR=/home/joe/config/caddy
    restart: unless-stopped